# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner
pod 'TZImagePickerController', '2.2.6' #iOS6、iOS7
#pod 'AliyunOSSiOS','2.4.0'
pod 'AFNetworking', '~> 3.1.0'
end
